spring:
  profiles:
    active: zxq

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sczyjsxy.jkx.cis.edubackend.model
  configuration:
    map-underscore-to-camel-case: true
    # 查看sql查询语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: /cis/edu
