spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jkx_system?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081
mybatis:
  type-aliases-package: cn.sczy.jkx.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

# 查看sql语句
debug:
  cn:
    sczy:
      jkx:
        mapper: true
